name: Lint

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  run_lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: install_packages
        name: Install packages
        run: |
          pnpm i --frozen-lockfile
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
          arguments: --github-annotate-new-only=false
